// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB8_m2w4Sf4omuR15H8SNm2STnT1Da_SU',
    appId: '1:176839306904:web:0b67d85c3815ddaa25eaed',
    messagingSenderId: '176839306904',
    projectId: 'my-lab-website',
    authDomain: 'my-lab-website.firebaseapp.com',
    storageBucket: 'my-lab-website.firebasestorage.app',
    measurementId: 'G-Y9T83TRGT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqN0D7CSKCbOnYERe6oegRovMQe4Lgyw',
    appId: '1:176839306904:android:cdd7cf9f40889fa625eaed',
    messagingSenderId: '176839306904',
    projectId: 'my-lab-website',
    storageBucket: 'my-lab-website.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5wu6d7L6Ju8VU_nSBIrKP5ncDh--1dTo',
    appId: '1:176839306904:ios:bc4318e4e2dfd2e825eaed',
    messagingSenderId: '176839306904',
    projectId: 'my-lab-website',
    storageBucket: 'my-lab-website.firebasestorage.app',
    iosBundleId: 'com.example.myLabWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5wu6d7L6Ju8VU_nSBIrKP5ncDh--1dTo',
    appId: '1:176839306904:ios:bc4318e4e2dfd2e825eaed',
    messagingSenderId: '176839306904',
    projectId: 'my-lab-website',
    storageBucket: 'my-lab-website.firebasestorage.app',
    iosBundleId: 'com.example.myLabWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB8_m2w4Sf4omuR15H8SNm2STnT1Da_SU',
    appId: '1:176839306904:web:176332b88db6485625eaed',
    messagingSenderId: '176839306904',
    projectId: 'my-lab-website',
    authDomain: 'my-lab-website.firebaseapp.com',
    storageBucket: 'my-lab-website.firebasestorage.app',
    measurementId: 'G-GPJWFLDF57',
  );
}
